can now stop pullbackups with pullbackups stop. Not fully tested though.

diff --git a/pullbackups b/pullbackups
--- a/pullbackups
+++ b/pullbackups
@@ -30,6 +30,10 @@ while [ "$1" != "" ]; do
     mode=help
     break
   fi
+  if [ "$1" == "-p" ] || [ "$1" == "--stop" ]; then
+    mode=stop
+    break
+  fi
   if [ "$1" == "-s" ] || [ "$1" == "--summarise" ]; then
     mode=summary
     break
@@ -43,10 +47,10 @@ while [ "$1" != "" ]; do
   shift
 done
 
-if [ "$mode" == "help" ] || [ "$mode" != "summary" ] && [ ${#parms[*]} -eq 0 ]; then
-    echo "pullbackups [-a] remotename..."
+if [ "$mode" == "help" ] || [ "$mode" != "summary" ] && [ "$mode" != "stop" ] && [ ${#parms[*]} -eq 0 ]; then
+    echo "pullbackups [--auto] [--summarise] [--stop] remotename..."
     echo "pull a set of backups generated by backup script from a remote server"
-    exit 1
+    exit 2 
 fi
 
 # work out where I am and find some things.
@@ -79,17 +83,27 @@ errfile=/var/log/pullbackups.err
 cfg_parser $confdir/pullbackups.ini
 cfg_section global
 eval backupdir=$backupdir # so that ~s work.
+eval logfile=$logfile
+eval errfile=$errfile
+eval summaryfile=$summaryfile
+eval rsyncerrfile=$rsyncerrfile
 eval mailto=$mailto # to split quoted words
 
 if [ "$backupdir" == "" ] ; then
   echo "Backup directory not found in $confdir/pullbackups.ini"
-  exit 1
+  exit 2
 fi
 
 if [ "$mode" == "summary" ] && [ "$mailto" != "" ]; then
+  # mail the summary log
   echo -e "\nDisk usage\n----------\n`df -h`" >> $summaryfile
   cat $summaryfile | mail -s "Pullbackups summary for `whoami`@`hostname`" $mailto
   echo -e "Summary of this week's fetches of remote backups for `whoami`@`hostname`.\n" > $summaryfile
+  exit 0
+fi
+if [ "$mode" == "stop" ]; then
+  # signal a stop to the main process
+  echo "stop" > $rsyncerrfile
   exit 0
 fi
 
@@ -109,12 +123,13 @@ fi
 echo " mode"
 
 cd $backupdir
-date=`date`
+exitcode=0
+exitmsg="Backups pulled down okay"
 for remote in ${parms[*]}; do
   # parse the ini file for this remote account
   if ! [ -f $confdir/pullbackups.d/$remote.ini ] ; then
     echo "Can't find remote configuration file: $confdir/pullbackups.d/$remote.ini"
-    exit 1
+    finish 2 "configuration error"
   fi
   echo "processing backups for remote account: $remote"
   remotedir=
@@ -122,7 +137,7 @@ for remote in ${parms[*]}; do
   cfg_section remote
   if [ "$remotedir" == "" ] ; then
     echo "Remote directory not found in $confdir/pullbackups.d/$remote.ini"
-    exit 1
+    finish 2 "configuration error"
   fi
   # iterate through list of remote configs
   eval remoteconfigs=$remoteconfigs # to split quoted words
@@ -139,19 +154,57 @@ for remote in ${parms[*]}; do
       mkdir -p $olddir
       sleep 2 # so new dir is datestamped later.
     fi
-    newdir=$localdir/nightly/`date +%Y-%m-%d-%H-%M-%S`
+    export newdir=$localdir/nightly/`date +%Y-%m-%d-%H-%M-%S`
     mkdir -p newdir
     if [ "$mode" == "manual" ] ; then
       verbose=
     else
       verbose=v
     fi
-    rsync -atz$verbose --copy-links --partial --delete --link-dest=$olddir $remotedir/$config/latest/ $newdir
+    rm -f $rsyncerrfile
+    export rsyncerrfile verbose olddir remotedir config newdir
+    # start rsync in a sub shell.
+    (rsync -atz$verbose --copy-links --partial --delete --link-dest=$olddir $remotedir/$config/latest/ $newdir; echo "$?">$rsyncerrfile) &
+    rsyncpid=$!
+    while ! [ -f $rsyncerrfile ]; do
+      sleep 10
+    done
+    rsyncerr=`cat $rsyncerrfile`
+    if [ "$rsyncerr" == "stop" ] ; then
+      # have been signalled to stop the rsync process
+      kill $rsyncpid
+      sleep 15
+      rsyncerr=`cat $rsyncerrfile`
+    fi
+    rm -f $rsyncerrfile
+    echo "Rsync finished - exit code $rsyncerr."
+    case $rsyncerr in
+      (20|23|24)
+        # transfer interrupted or incomplete, or other recoverable error.
+        # hard-link remaining files into the new nightly dir. (so they're not
+        # missing on the next run).
+        echo "Incomplete transfer - adding missing files."
+        cp -rnl $olddir/* $newdir
+        exitcode=1
+        exitmsg="Transfer incomplete."
+        ;;
+      (0)
+        # success.
+        exitcode=0
+        exitmsg="Transfer complete."
+        ;;
+      (*)
+        # other error - delete bad copy.
+        rm -rf $newdir
+        finish 2 "Transfer failed."
+        ;;
+    esac
+
     echo "generating weeklies/monthlies for $config"
     # remove old backup files from auto directories.
     cd $localdir/nightly || {
       echo "Error - Can't find nightly backup dir."
-      exit 1
+      finish 2 "configuration error"
     }
     ls -r | tail -n +$(( $nightlyfiles + 1 )) | xargs rm -rf
     if [ `date -d "$date" +%a` == "$weeklyday" ] && [ $weeklyfiles -gt 0 ] ; then
@@ -160,7 +213,7 @@ for remote in ${parms[*]}; do
     if [ $weeklyfiles -gt 0 ] ; then
       cd $localdir/weekly || {
         echo "Error - Can't find weekly backup dir."
-        exit 1
+        finish 2 "configuration error"
       }
       ls -r | tail -n +$(( $weeklyfiles + 1 )) | xargs rm -rf
     fi
@@ -170,11 +223,11 @@ for remote in ${parms[*]}; do
     if [ $monthlyfiles -gt 0 ] ; then
       cd $localdir/monthly || {
         echo "Error - Can't find monthly backup dir."
-        exit 1
+        finish 2 "configuration error"
       }
       ls -r | tail -n +$(( $monthlyfiles + 1 )) | xargs rm -rf
     fi
   done
 done
-finish 0 "Backups pulled down okay"
+finish $exitcode "$exitmsg"
 
