finished pullbackups

diff --git a/pullbackups b/pullbackups
--- a/pullbackups
+++ b/pullbackups
@@ -1,7 +1,8 @@
 #!/bin/bash
 #
 # Script to pull down a set of backups generated by 'backup' from a remote
-# server.
+# server. Intended to run nightly and generate a set of weekly and monthly
+# snapshots from a smaller set of nightlies on the server.
 #
 
 # set some defaults
@@ -43,10 +44,54 @@ if [ "$rsyncsrc" == "" ] ; then
   echo "Rsync source string not found in $confdir/pullbackups.ini"
   exit 1
 fi
+if [ "$backupdir" == "" ] ; then
+  echo "Backup directory not found in $confdir/pullbackups.ini"
+  exit 1
+fi
 
-echo "Pulling down backups from $rsyncsrc"
+echo "Pulling down backups from $rsyncsrc to $backupdir"
 
 cd $backupdir
-rsync -av $rsyncsrc .
+rsync -av $rsyncsrc/ .
+date=`date`
 for config in *; do
+  # skip non-directories
+  if ! [ -d $backupdir/$config ] ; then
+    continue
+  fi
+  echo "generating weeklies/monthlies for $config"
+  # find latest nightly backup and copy to weekly/monthly dir if appropriate
+  tarfile=`ls -t $backupdir/$config/nightly | tail -n 1`
+  # remove old backup files from auto directories.
+  cd $backupdir/$config/nightly || {
+    echo "Error - Can't find nightly backup dir."
+    exit 1
+  }
+  ls -t | tail -n +$(( $nightlyfiles + 1 )) | xargs rm -f
+  if [ "`ls -1 $backupdir/$config/weekly | wc -l`" == "0" ] ; then
+    # if the weeklies weren't kept on the server, generate them here.
+    if [ `date -d "$date" +%a` == "$weeklyday" ] && [ $weeklyfiles -gt 0 ] ; then
+      cp $tarfile $backupdir/$config/weekly
+    fi
+    if [ $weeklyfiles -gt 0 ] ; then
+      cd $backupdir/$config/weekly || {
+        echo "Error - Can't find weekly backup dir."
+        exit 1
+      }
+      ls -t | tail -n +$(( $weeklyfiles + 1 )) | xargs rm -f
+    fi
+  fi
+  if [ "`ls -1 $backupdir/$config/monthly | wc -l`" == "0" ] ; then
+    # same with the monthlies
+    if [ `date -d "$date" +%d` == "$monthlyday" ] && [ $monthlyfiles -gt 0 ] ; then
+      cp $tarfile $backupdir/$config/monthly
+    fi
+    if [ $monthlyfiles -gt 0 ] ; then
+      cd $backupdir/$config/monthly || {
+        echo "Error - Can't find monthly backup dir."
+        exit 1
+      }
+      ls -t | tail -n +$(( $monthlyfiles + 1 )) | xargs rm -f
+    fi
+  fi
 done
